### ISSUE TITLE
https://redirect.pizza/ service is not working

### ISSUE THREAD

**Issue by bio937** [enflow/redirect-pizza-php-sdk#3]
Dear all,

Thanks a lot for developing such a great tool for redirecting HTTPS automatically. We have been using the service for quite a while and found it very useful.

However today when I tried to access my website using the URL redirected by https://redirect.pizza/, it failed to redirect to the destination URL. I later found out that the whole website https://redirect.pizza/ also cannot be accessed. 

May I know whether this is just a temporary server disruption? I would greatly appreciate it if you could help to look into this issue. Thanks a lot.

**Comment by bio937** [comment]
https://redirect.pizza/ is working properly now. Thanks a lot for your work. This website is awesome for developers!

**Comment by mbardelmeijer** [comment]
Hey! Thanks for the report, seems like a temporary issue on server level, should all be good now! You can contact us on support@redirect.pizza or via chat on the website if you have any issues regarding the service.

**Comment by bio937** [comment]
@mbardelmeijer 
Thanks a lot for the information. redirect.pizza is a brilliant tool!
